### ISSUE TITLE
plot polygons without overlap

### ISSUE THREAD

**Issue by Bo-UT** [dcjones/proseg#13]
Hi, 

The 3D flattened polygons (cell-polygons.geojson.gz) have too much overlap. How to plot them without overlap? Like the Fig.1c in your BioRxiv paper. Thank you!

Xenium explorer

<img width="202" alt="image" src="https://github.com/dcjones/proseg/assets/55055062/da0b043c-8cf3-437c-9804-fee1a5f9a1e9">

https://doi.org/10.1101/2024.04.25.591218
<img width="509" alt="Screenshot 2024-06-07 at 9 36 17 PM" src="https://github.com/dcjones/proseg/assets/55055062/e4ef77c4-7f7a-4c80-880f-aaf573ab64fc">

**Comment by Bo-UT** [comment]
Solved. Find polygon layers in cell-polygons-layers.geojson.gz. Thanks.

**Comment by dcjones** [comment]
In proseg 1.1.0 the default behavior is now for `--output-cell-polygons` to produce non-overlapping consensus 2D polygons, which should look more like the ones in the paper.
