### ISSUE TITLE
About spurious coexpression metric for CosMx data

### ISSUE THREAD

**Issue by yihming** [dcjones/proseg#21]
Hello,

Thanks for developing this great tool!

When reading through [your paper](https://www.biorxiv.org/content/10.1101/2024.04.25.591218v1), in Figure 9, I see that you used the degree of spurious coexpression as one of the metrics to measure the segmentation quality of different methods, which was discussed in details in Section 3.2.3.

I just wonder if it is possible to share your implementation on this metric (or maybe I missed it if you had already made it public), so that we could also apply to our CosMx data to compare the methods. Thanks!

Sincerely,
Yiming

**Comment by dcjones** [comment]
I'll definitely try to release some code to reproduce this analysis, I just don't have it in a very usable form right now.

**Comment by yihming** [comment]
Thank you in advance!
