### ISSUE TITLE
Viewing 2D non-overlapping cell boundaries in Xenium Explorer with proseg-to-baysor 

### ISSUE THREAD

**Issue by imran-aifi** [dcjones/proseg#24]
Is it possible to view the 2D, non-overlapping cell boundaries (given by `cell-polygons-layers.geojson.gz`) in Xenium Explorer using `proseg-to-baysor` ?  

This is my usage, substituting cell-polygons-layers.geojson.gz with cell-polygons.geojson.gz.
```bash
proseg-to-baysor \
    ${OUTDIR}/transcript-metadata.csv.gz \
    ${OUTDIR}/cell-polygons-layers.geojson.gz \
    --output-transcript-metadata ${OUTDIR}/baysor-transcript-metadata.csv \
    --output-cell-polygons ${OUTDIR}/baysor-cell-polygons.geojson
```

After running xeniumranger on this output, I still see overlapping segmentation in Xenium Explorer, and the number of cells detected is approx 4X larger than with the default segmentation (or with exporting cell-polygons.geojson.gz) (598k vs 152k cells).
![TIS05392_proseg](https://github.com/dcjones/proseg/assets/92489798/cafa9167-b177-46e3-bb84-6d966421e23c)

**Comment by dcjones** [comment]
I'm not sure if there is currently an easy way to get the polygon layers that proseg reports into xenium explorer, but I'll be releasing a new version soon that outputs non-overalapping 2d consensus polygons, that will be more suitable for xenium explorer I think.

**Comment by ConstensouxAlexis** [comment]
Hello, is the latest version of Proseg (1.0.6) the version that can output non-overlapping 2d polygons ? Thanks !
