### ISSUE TITLE
Thread panicked with z_prob_sum.is_finite() assertion failure

### ISSUE THREAD

**Issue by yihming** [dcjones/proseg#32]
Hello,

My proseg run on a Xenium 5k dataset encounters the following issue:
```
thread '<unnamed>' panicked at thread '/software/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proseg-1.1.3/src/sampler.rs:1703:17:
assertion failed: z_prob_sum.is_finite()
<unnamed>' panicked at /software/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proseg-1.1.3/src/sampler.rs:1703:17:
assertion failed: z_prob_sum.is_finite()
```
and finally failed with Rust exit code 101.

I use Proseg v1.1.3, with the following command:
```
proseg --xenium --nthreads 32 transcripts.parquet
```
with a machine of 32 vCPU and 240GB memory. The dataset has `~206m` transcripts, with median transcripts per cell `263` and nuclear transcripts per 100 µm2 `583.5`.

Do you have any suggestion on diagnosing this issue?

In the mean time, I'm running another process with Proseg v1.1.2 to check if the issue is related to different versions of Proseg.

**Comment by dcjones** [comment]
Apologies for the lack of response. This and issue #33 are the same, namely that the current release of proseg generally breaks with a large number of genes like Xenium 5k or CosMx 6k panels. I'll close this issue and keep that one open to keep track of the problem.
