### ISSUE TITLE
Errors related to rust sorting

### ISSUE THREAD

**Issue by RitaRuoxinLi** [dcjones/proseg#41]
Hi, I am trying proseg on our newly generated tissue samples, so far it works great and I am very appreciative of the effort. However, for only one of the samples generated, the xenium ranger seems running fine, but when applying proseg on the transcript.parquet, I got the following errors:
<img width="1063" alt="Screenshot 2024-10-29 at 1 00 12 PM" src="https://github.com/user-attachments/assets/36463e91-d0a4-4576-a444-99b2de6a68de">

Proseg has being running fine on other samples, but only failed for this one, and the Xenium ranger's output looks normal(median # transcripts per cell is 273) could you please provide some hints on how to resolve the issue?

I will be very appreciative!

**Comment by dcjones** [comment]
I believe this issue was fixed in version 1.1.7. Please check that you're using the latest version of proseg (`proseg --version` should tell you).

**Comment by RitaRuoxinLi** [comment]
Thank you for your reply! I went back to check proseg --version, it is already proseg 1.1.8

**Comment by dcjones** [comment]
Oh, I see! It is the same error, but in a different place. I've just published version 1.1.9 which I believe should fix this.

**Comment by RitaRuoxinLi** [comment]
I tested version 1.1.9 and the error is already resolved, thank you very much for your assistance!
